spring:
  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-1r8rxmmy.sql.tencentcdb.com:26631/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Aa7531594862!
#    url: jdbc:mysql://127.0.0.1:3306/springboot?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    username: root
#    password: 123456

  main:
    allow-circular-references: true


server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liu.practice.

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#代码沙箱配置
codesandbox:
   type: remote